# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hicuteUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hicuteUi(object):
    def setupUi(self, hicuteUi):
        hicuteUi.setObjectName("hicuteUi")
        hicuteUi.setWindowModality(QtCore.Qt.WindowModal)
        hicuteUi.setEnabled(True)
        hicuteUi.resize(1366, 768)
        self.centralwidget = QtWidgets.QWidget(hicuteUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 1366, 768))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images\\Wallpaper.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1100, 660, 100, 61))
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1250, 660, 100, 61))
        self.pushButton_2.setStyleSheet("background-color:rgb(255, 0, 0);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1100, 0, 271, 191))
        self.label_2.setStyleSheet("background-color:transparent;\n"
"border-radius: None;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images\\unnamed.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 291, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.textBrowser.setFont(font)
        self.textBrowser.setMouseTracking(False)
        self.textBrowser.setAcceptDrops(True)
        self.textBrowser.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;\n"
"border-radius:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(350, 0, 291, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;\n"
"border-radius:none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        hicuteUi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(hicuteUi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 26))
        self.menubar.setObjectName("menubar")
        hicuteUi.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(hicuteUi)
        self.statusbar.setObjectName("statusbar")
        hicuteUi.setStatusBar(self.statusbar)

        self.retranslateUi(hicuteUi)
        QtCore.QMetaObject.connectSlotsByName(hicuteUi)

    def retranslateUi(self, hicuteUi):
        _translate = QtCore.QCoreApplication.translate
        hicuteUi.setWindowTitle(_translate("hicuteUi", "HICUTE - 6A2 CHU VĂN AN"))
        self.pushButton.setText(_translate("hicuteUi", "Run"))
        self.pushButton_2.setText(_translate("hicuteUi", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hicuteUi = QtWidgets.QMainWindow()
    ui = Ui_hicuteUi()
    ui.setupUi(hicuteUi)
    hicuteUi.show()
    sys.exit(app.exec_())
